package com.healthconnect.claims.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Claim header — one record per submitted claim transaction (837P/I/D).
 *
 * Line items are stored in claim_line_items (see ClaimLineItem).
 *
 * NOTE: The 'raw_payload' column stores the original X12/JSON payload as TEXT.
 * JSONB was discussed for better query performance but DBA approval is pending
 * (HCEP-1901). Using TEXT until approved.
 */
@Entity
@Table(name = "claims")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Claim {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Internal claim reference number — generated by HealthConnect.
     * Distinct from the payer's claim number which is received after adjudication.
     */
    @Column(name = "claim_number", nullable = false, unique = true)
    private String claimNumber;

    @Column(name = "payer_id", nullable = false)
    private String payerId;

    @Column(name = "member_id", nullable = false)
    private String memberId;

    @Column(name = "provider_npi")
    private String providerNpi;

    @Column(name = "provider_tin")
    private String providerTin;

    @Column(name = "rendering_provider_npi")
    private String renderingProviderNpi;

    @Enumerated(EnumType.STRING)
    @Column(name = "claim_type", nullable = false)
    private ClaimType claimType;

    @Column(name = "service_from_date")
    private String serviceFromDate;

    @Column(name = "service_to_date")
    private String serviceToDate;

    @Column(name = "total_charge", precision = 12, scale = 2)
    private BigDecimal totalCharge;

    @Column(name = "allowed_amount", precision = 12, scale = 2)
    private BigDecimal allowedAmount;

    @Column(name = "paid_amount", precision = 12, scale = 2)
    private BigDecimal paidAmount;

    @Column(name = "patient_responsibility", precision = 12, scale = 2)
    private BigDecimal patientResponsibility;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    @Builder.Default
    private ClaimStatus status = ClaimStatus.RECEIVED;

    /** Payer-assigned claim reference number — populated after adjudication. */
    @Column(name = "payer_claim_number")
    private String payerClaimNumber;

    /** Control number from the original 837 transaction set. */
    @Column(name = "control_number")
    private String controlNumber;

    /** ICN — Insurance Control Number assigned by payer post-adjudication. */
    @Column(name = "icn")
    private String icn;

    @Column(name = "denial_reason_code")
    private String denialReasonCode;

    @Column(name = "denial_reason_description", columnDefinition = "TEXT")
    private String denialReasonDescription;

    /**
     * Original submission payload (X12 837 or JSON).
     * Stored as TEXT — JSONB pending DBA approval (HCEP-1901).
     */
    @Column(name = "raw_payload", columnDefinition = "TEXT")
    private String rawPayload;

    @Column(name = "submitted_at")
    private Instant submittedAt;

    @Column(name = "adjudicated_at")
    private Instant adjudicatedAt;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Builder.Default
    @OneToMany(mappedBy = "claim", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private List<ClaimLineItem> lineItems = new ArrayList<>();
}
